# Generated by Django 5.1.5 on 2025-01-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(verbose_name='список заказанных блюд с ценами'),
        ),
    ]
